In [1]:
import numpy as np
import week4

In [2]:
np.set_printoptions(precision=3)

In [3]:
# The reference solution uses the default solver in `scipy.optimize.lingprog`

games = [
    np.array([[30, -10, 20], [-10, 20, -20]], dtype=np.float32),
    np.array([[0, -1, 1], [1, 0, -1], [-1, 1, 0]], dtype=np.float32),
    np.array([[0, 7, 7], [7, 0, 7], [3, 3, 3]], dtype=np.float32),
    np.array([[1, -1], [-1, 1]], dtype=np.float32)
]

for matrix in games:
    row_strategy, col_strategy = week4.find_nash_equilibrium(matrix)
    correlated_equilibrium = week4.find_correlated_equilibrium(matrix, -matrix)
    
    print(f"Row Player's strategy in a Nash Equilibrium: {row_strategy}")
    print(f"Column Player' strategy in a Nash Equilibrium: {col_strategy}")
    
    print(f'Correlated Equilibrium:')
    print(correlated_equilibrium)
    print()

Row Player's strategy in a Nash Equilibrium: [0.571 0.429]
Column Player' strategy in a Nash Equilibrium: [0.    0.571 0.429]
Correlated Equilibrium:
[[0.    0.327 0.245]
 [0.    0.245 0.184]]

Row Player's strategy in a Nash Equilibrium: [0.333 0.333 0.333]
Column Player' strategy in a Nash Equilibrium: [0.333 0.333 0.333]
Correlated Equilibrium:
[[0.111 0.111 0.111]
 [0.111 0.111 0.111]
 [0.111 0.111 0.111]]

Row Player's strategy in a Nash Equilibrium: [0.5 0.5 0. ]
Column Player' strategy in a Nash Equilibrium: [0.5 0.5 0. ]
Correlated Equilibrium:
[[ 0.25  0.25  0.  ]
 [ 0.25  0.25  0.  ]
 [-0.    0.    0.  ]]

Row Player's strategy in a Nash Equilibrium: [0.5 0.5]
Column Player' strategy in a Nash Equilibrium: [0.5 0.5]
Correlated Equilibrium:
[[0.25 0.25]
 [0.25 0.25]]



In [4]:
games = [
    (np.array([[4, 1], [5, 0]], dtype=np.float32), np.array([[4, 5], [1, 0]], dtype=np.float32)),
    (np.array([[0, -1], [1, -10]], dtype=np.float32), np.array([[0, 1], [-1, -10]], dtype=np.float32)),
    (np.array([[-2, 0], [-3, -1]], dtype=np.float32), np.array([[-2, -3], [0, -1]], dtype=np.float32))
]

for (matrix1, matrix2) in games:
    correlated_equilibrium = week4.find_correlated_equilibrium(matrix1, matrix2)
    
    print(f'Correlated Equilibrium:')
    print(correlated_equilibrium)
    print()

Correlated Equilibrium:
[[0. 1.]
 [0. 0.]]

Correlated Equilibrium:
[[0. 1.]
 [0. 0.]]

Correlated Equilibrium:
[[1. 0.]
 [0. 0.]]

