In [1]:
import numpy as np

import efg
import week1
import week2
import week4
import week7

In [2]:
np.set_printoptions(precision=3, linewidth=100)

In [3]:
game = efg.ConversionExampleTree1()  # See Week 7, Slide 4

matrix1, matrix2 = week7.convert_to_normal_form(game)
assert np.all(matrix1 == -matrix2), 'The game has to be zero-sum!'

# Transpose the matrices to match the slides
print('Payoff matrix for Player 1:', np.transpose(matrix1), sep='\n')
print('Payoff matrix for Player 2:', np.transpose(matrix2), sep='\n')

row_strategy, col_strategy = week4.find_nash_equilibrium(matrix1)
print(f"Row Player's strategy in a Nash Equilibrium: {row_strategy}")
print(f"Column Player's strategy in a Nash Equilibrium: {col_strategy}")

row_utility, col_utility = week1.evaluate(row_strategy, col_strategy, matrix1)
print(f'Utilities: {row_utility:.3f}, {col_utility:.3f}')

Payoff matrix for Player 1:
[[1. 3. 5. 7.]
 [1. 3. 5. 8.]
 [1. 3. 6. 7.]
 [1. 3. 6. 8.]
 [1. 4. 5. 7.]
 [1. 4. 5. 8.]
 [1. 4. 6. 7.]
 [1. 4. 6. 8.]
 [2. 3. 5. 7.]
 [2. 3. 5. 8.]
 [2. 3. 6. 7.]
 [2. 3. 6. 8.]
 [2. 4. 5. 7.]
 [2. 4. 5. 8.]
 [2. 4. 6. 7.]
 [2. 4. 6. 8.]]
Payoff matrix for Player 2:
[[-1. -3. -5. -7.]
 [-1. -3. -5. -8.]
 [-1. -3. -6. -7.]
 [-1. -3. -6. -8.]
 [-1. -4. -5. -7.]
 [-1. -4. -5. -8.]
 [-1. -4. -6. -7.]
 [-1. -4. -6. -8.]
 [-2. -3. -5. -7.]
 [-2. -3. -5. -8.]
 [-2. -3. -6. -7.]
 [-2. -3. -6. -8.]
 [-2. -4. -5. -7.]
 [-2. -4. -5. -8.]
 [-2. -4. -6. -7.]
 [-2. -4. -6. -8.]]
Row Player's strategy in a Nash Equilibrium: [0. 0. 0. 1.]
Column Player's strategy in a Nash Equilibrium: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Utilities: 7.000, -7.000


In [4]:
game = efg.ConversionExampleTree2()  # See Week 7, Slide 5

matrix1, matrix2 = week7.convert_to_normal_form(game)

print('Payoff matrix for Player 1:', matrix1, sep='\n')
print('Payoff matrix for Player 2:', matrix2, sep='\n')

for (row_strategy, col_strategy) in week2.support_enumeration(matrix1, matrix2):
    row_strategy, col_strategy = np.asarray(row_strategy), np.asarray(col_strategy)
    row_utility, col_utility = week1.evaluate_pair(row_strategy, col_strategy, matrix1, matrix2)

    print(f'Row strategy: {row_strategy}, Col strategy: {col_strategy}')
    print(f'Utilities: {row_utility:.3f}, {col_utility:.3f}')

Payoff matrix for Player 1:
[[2. 5.]
 [0. 6.]
 [3. 3.]
 [3. 3.]]
Payoff matrix for Player 2:
[[2. 6.]
 [3. 1.]
 [3. 3.]
 [3. 3.]]
Row strategy: [0.333 0.667 0.    0.   ], Col strategy: [0.333 0.667]
Utilities: 4.000, 2.667
Row strategy: [-0.  0.  1.  0.], Col strategy: [0.667 0.333]
Utilities: 3.000, 3.000
Row strategy: [-0.  0.  0.  1.], Col strategy: [0.667 0.333]
Utilities: 3.000, 3.000
Row strategy: [0. 0. 1. 0.], Col strategy: [1. 0.]
Utilities: 3.000, 3.000
Row strategy: [0. 0. 0. 1.], Col strategy: [1. 0.]
Utilities: 3.000, 3.000


In [5]:
# Extensive-form Rock-Paper-Scissors where Player 2 does not observe what Player 1 has played
game = efg.RockPaperScissors()

matrix1, matrix2 = week7.convert_to_normal_form(game)
assert np.all(matrix1 == -matrix2), 'The game has to be zero-sum!'

print('Payoff matrix for Player 1:', matrix1, sep='\n')
print('Payoff matrix for Player 2:', matrix2, sep='\n')

row_strategy, col_strategy = week4.find_nash_equilibrium(matrix1)
print(f"Row Player's strategy in a Nash Equilibrium: {row_strategy}")
print(f"Column Player's strategy in a Nash Equilibrium: {col_strategy}")

row_utility, col_utility = week1.evaluate(row_strategy, col_strategy, matrix1)
print(f'Utilities: {row_utility:.3f}, {col_utility:.3f}')

Payoff matrix for Player 1:
[[ 0. -1.  1.]
 [ 1.  0. -1.]
 [-1.  1.  0.]]
Payoff matrix for Player 2:
[[ 0.  1. -1.]
 [-1.  0.  1.]
 [ 1. -1.  0.]]
Row Player's strategy in a Nash Equilibrium: [0.333 0.333 0.333]
Column Player's strategy in a Nash Equilibrium: [0.333 0.333 0.333]
Utilities: 0.000, 0.000


In [6]:
game = efg.KuhnPoker()
strategies = efg.initialize_strategies(game.info_sets, 'uniform')

matrix1, matrix2 = week7.convert_to_normal_form(game, strategies[efg.Player.Chance])
assert np.all(matrix1 == -matrix2), 'The game has to be zero-sum!'

print('Payoff matrix for Player 1:', matrix1, sep='\n')
print('Payoff matrix for Player 2:', matrix2, sep='\n')

row_strategy, col_strategy = week4.find_nash_equilibrium(matrix1)
print("Row Player's strategy in a Nash Equilibrium:", row_strategy, sep='\n')
print("Column Player's strategy in a Nash Equilibrium:", col_strategy, sep='\n')

row_utility, col_utility = week1.evaluate(row_strategy, col_strategy, matrix1)
print(f'Utilities: {row_utility:.3f}, {col_utility:.3f}')

Payoff matrix for Player 1:
[[ 0.     0.     0.333 ... -0.333  0.     0.   ]
 [ 0.     0.    -0.167 ... -0.833 -1.    -1.   ]
 [ 0.333  0.167  0.5   ... -0.5   -0.167 -0.333]
 ...
 [-0.333 -0.5   -0.667 ...  0.667  0.5    0.333]
 [ 0.    -0.333  0.    ...  1.     1.333  1.   ]
 [ 0.    -0.333  0.    ...  1.     1.333  1.   ]]
Payoff matrix for Player 2:
[[ 0.     0.    -0.333 ...  0.333  0.     0.   ]
 [ 0.     0.     0.167 ...  0.833  1.     1.   ]
 [-0.333 -0.167 -0.5   ...  0.5    0.167  0.333]
 ...
 [ 0.333  0.5    0.667 ... -0.667 -0.5   -0.333]
 [ 0.     0.333  0.    ... -1.    -1.333 -1.   ]
 [ 0.     0.333  0.    ... -1.    -1.333 -1.   ]]
Row Player's strategy in a Nash Equilibrium:
[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.5   0.    0.333 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.167 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.  

In [7]:
game = efg.ConversionExampleTree1()  # See Week 7, Slide 4
strategies = efg.initialize_strategies(game.info_sets, 'uniform')
chance_strategy = strategies[efg.Player.Chance]

# NOTE: I deliberately do not show what `sequences1` and `sequences2` look
# like as it would reveal a representation choice that you need to come up with
sequences1, sequences2, matrix1, matrix2 = week7.convert_to_sequence_form(game, chance_strategy)
E, e = week7.calculate_constraints(game, efg.Player.Player1, sequences1)
F, f = week7.calculate_constraints(game, efg.Player.Player2, sequences2)

# Transpose the matrices to match the slides
print('Payoff matrix for Player 1:', np.transpose(matrix1), sep='\n')
print('Payoff matrix for Player 2:', np.transpose(matrix2), sep='\n')

print('Constraint matrix and vector for Player 1:', E, e, sep='\n')
print('Constraint matrix and vector for Player 2:', F, f, sep='\n')

assert np.all(matrix1 == -matrix2), 'The game has to be zero-sum!'

strategy1, strategy2 = week7.find_nash_equilibrium_sequence_form(game, chance_strategy)

print("Row Player's strategy in a Nash Equilibrium:", strategy1)
print("Column Player's strategy in a Nash Equilibrium:", strategy2)

row_utility, col_utility = week1.evaluate(strategy1, strategy2, matrix1)
print(f'Utilities: {row_utility:.3f}, {col_utility:.3f}')

Payoff matrix for Player 1:
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 6. 0.]
 [0. 0. 0. 0. 7.]
 [0. 0. 0. 0. 8.]]
Payoff matrix for Player 2:
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0. -2.  0.  0.  0.]
 [ 0.  0. -3.  0.  0.]
 [ 0.  0. -4.  0.  0.]
 [ 0.  0.  0. -5.  0.]
 [ 0.  0.  0. -6.  0.]
 [ 0.  0.  0.  0. -7.]
 [ 0.  0.  0.  0. -8.]]
Constraint matrix and vector for Player 1:
[[ 1.  0.  0.  0.  0.]
 [-1.  1.  1.  1.  1.]]
[1. 0.]
Constraint matrix and vector for Player 2:
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  1.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  1.  1.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  1.  1.]]
[1. 0. 0. 0. 0.]
Row Player's strategy in a Nash Equilibrium: [1. 0. 0. 0. 1.]
Column Player's strategy in a Nash Equilibrium: [1. 1. 0. 1. 0. 1. 0. 1. 0.]
Utilities: 7.000, -7.000


In [8]:
game = efg.ConversionExampleTree2()  # See Week 7, Slide 5
strategies = efg.initialize_strategies(game.info_sets, 'uniform')
chance_strategy = strategies[efg.Player.Chance]

# NOTE: I deliberately do not show what `sequences1` and `sequences2` look
# like as it would reveal a representation choice that you need to come up with
sequences1, sequences2, matrix1, matrix2 = week7.convert_to_sequence_form(game, chance_strategy)
E, e = week7.calculate_constraints(game, efg.Player.Player1, sequences1)
F, f = week7.calculate_constraints(game, efg.Player.Player2, sequences2)

# The order of sequences does not have to be the same as in the slides
print('Payoff matrix for Player 1:', matrix1, sep='\n')
print('Payoff matrix for Player 2:', matrix2, sep='\n')

print('Constraint matrix and vector for Player 1:', E, e, sep='\n')
print('Constraint matrix and vector for Player 2:', F, f, sep='\n')

# NOTE: Sequence Form LP finds a Nash equilibrium *only* in two-player zero-sum games
# See https://kam.mff.cuni.cz/~balko/ath2425/main.pdf if you are interested in the general case

Payoff matrix for Player 1:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 2. 5.]
 [0. 0. 6.]
 [3. 0. 0.]]
Payoff matrix for Player 2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 2. 6.]
 [0. 3. 1.]
 [3. 0. 0.]]
Constraint matrix and vector for Player 1:
[[ 1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  1.]
 [ 0. -1.  1.  1.  0.]]
[1. 0. 0.]
Constraint matrix and vector for Player 2:
[[ 1.  0.  0.]
 [-1.  1.  1.]]
[1. 0.]


In [9]:
# Extensive-form Rock-Paper-Scissors where Player 2 does not observe what Player 1 has played
game = efg.RockPaperScissors()
strategies = efg.initialize_strategies(game.info_sets, 'uniform')
chance_strategy = strategies[efg.Player.Chance]

# NOTE: I deliberately do not show what `sequences1` and `sequences2` look
# like as it would reveal a representation choice that you need to come up with
sequences1, sequences2, matrix1, matrix2 = week7.convert_to_sequence_form(game, chance_strategy)
E, e = week7.calculate_constraints(game, efg.Player.Player1, sequences1)
F, f = week7.calculate_constraints(game, efg.Player.Player2, sequences2)

print('Payoff matrix for Player 1:', matrix1, sep='\n')
print('Payoff matrix for Player 2:', matrix2, sep='\n')

print('Constraint matrix and vector for Player 1:', E, e, sep='\n')
print('Constraint matrix and vector for Player 2:', F, f, sep='\n')

assert np.all(matrix1 == -matrix2), 'The game has to be zero-sum!'

strategy1, strategy2 = week7.find_nash_equilibrium_sequence_form(game, chance_strategy)

print("Row Player's strategy in a Nash Equilibrium:", strategy1)
print("Column Player's strategy in a Nash Equilibrium:", strategy2)

row_utility, col_utility = week1.evaluate(strategy1, strategy2, matrix1)
print(f'Utilities: {row_utility:.3f}, {col_utility:.3f}')

Payoff matrix for Player 1:
[[ 0.  0.  0.  0.]
 [ 0.  0. -1.  1.]
 [ 0.  1.  0. -1.]
 [ 0. -1.  1.  0.]]
Payoff matrix for Player 2:
[[ 0.  0.  0.  0.]
 [ 0.  0.  1. -1.]
 [ 0. -1.  0.  1.]
 [ 0.  1. -1.  0.]]
Constraint matrix and vector for Player 1:
[[ 1.  0.  0.  0.]
 [-1.  1.  1.  1.]]
[1. 0.]
Constraint matrix and vector for Player 2:
[[ 1.  0.  0.  0.]
 [-1.  1.  1.  1.]]
[1. 0.]
Row Player's strategy in a Nash Equilibrium: [1.    0.333 0.333 0.333]
Column Player's strategy in a Nash Equilibrium: [1.    0.333 0.333 0.333]
Utilities: 0.000, 0.000


In [10]:
game = efg.KuhnPoker()
strategies = efg.initialize_strategies(game.info_sets, 'uniform')
chance_strategy = strategies[efg.Player.Chance]

# NOTE: I deliberately do not show what `sequences1` and `sequences2` look
# like as it would reveal a representation choice that you need to come up with
sequences1, sequences2, matrix1, matrix2 = week7.convert_to_sequence_form(game, chance_strategy)
E, e = week7.calculate_constraints(game, efg.Player.Player1, sequences1)
F, f = week7.calculate_constraints(game, efg.Player.Player2, sequences2)

print('Payoff matrix for Player 1:', matrix1, sep='\n')
print('Payoff matrix for Player 2:', matrix2, sep='\n')

print('Constraint matrix and vector for Player 1:', E, e, sep='\n')
print('Constraint matrix and vector for Player 2:', F, f, sep='\n')

assert np.all(matrix1 == -matrix2), 'The game has to be zero-sum!'

strategy1, strategy2 = week7.find_nash_equilibrium_sequence_form(game, chance_strategy)

print("Row Player's strategy in a Nash Equilibrium:", strategy1, sep='\n')
print("Column Player's strategy in a Nash Equilibrium:", strategy2, sep='\n')

row_utility, col_utility = week1.evaluate(strategy1, strategy2, matrix1)
print(f'Utilities: {row_utility:.3f}, {col_utility:.3f}')

Payoff matrix for Player 1:
[[ 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.167  0.     0.     0.    -0.167  0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.    -0.333  0.     0.     0.    -0.333  0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.    -0.167  0.     0.     0.    -0.167  0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.    -0.333  0.167  0.     0.    -0.333  0.167  0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.    -0.167  0.     0.     0.     0.167  0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.    -0.333  0.     0.     0.     0.333  0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.    -0.167  0.     0.     0.    -0.167  0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.    -0.333  0.167  0.     0.     0.333  0.167]
 [ 0.     0.167  0.     0.     0.     0.     0.     0.     0.     0.167  0.     0.     0.   ]
 [ 0.     0.     0.333  0.     0